version: '3.5'

# docker stack deploy --compose-file stack-invoiceplane.yml invoiceplane

volumes:
  invoiceplane_uploads:
  invoiceplane_css:
  invoiceplane_views:
  mariadb_10_4:

services:
  proxyv2:
    image: traefik:v2.5 # The official Traefik docker image
    command:
      - "--api.insecure=true"
      - "--providers.docker"
    ports:
      - "80:80"     # The HTTP port
      - "443:443"   # The HTTP port
      - "8181:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
    labels:
      - "traefik.enable=false"
  invoiceplane:
    image: mhzawadi/invoiceplane
    volumes:
      - invoiceplane_uploads:/var/www/html/uploads
      - invoiceplane_css:/var/www/html/assets/core/css
      - invoiceplane_views:/var/www/html/application/views
    environment:
      - TZ=utc
      - MYSQL_HOST=mariadb_10_4
      - MYSQL_USER=invoiceplane
      - MYSQL_PASSWORD=invoiceplane
      - MYSQL_DB=invoiceplane
      - IP_URL=http://invoiceplane.docker.local
      - REMOVE_INDEXPHP=true
      - SETUP_COMPLETED=false
    labels:
      - "traefik.http.routers.invoiceplane.rule=Host(`invoiceplane.docker.local`)"
      - "traefik.http.routers.invoiceplane.service=invoiceplane"
      - "traefik.http.services.invoiceplane.loadbalancer.server.port=80"
  mariadb_10_4:
    # MySQL 5.7
    image: mariadb:10.4.10
    volumes:
      - mariadb_10_4:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql_password
      - MYSQL_DATABASE=invoiceplane
      - MYSQL_USER=invoiceplane
      - MYSQL_PASSWORD=invoiceplane
    labels:
      - "traefik.enable=false"
